"""Version 1.0. Copy is frozen into each issued document, never loaded on acceptance."""

VERSION = "1.0"
TERMS = [
    ("Relationship to the Booking Agreement", "This Property Access & Shoot Authorisation supplements but does not replace the Booking Agreement. The Booking Agreement continues to govern package/scope, agreed price, payment, cancellation, delivery, licensing, revision rules and general commercial terms. This is a pre-shoot operational authorisation, not a payment condition."),
    ("Authority and access", "The person completing this form confirms that they are the owner of the Property or have the owner's authority to instruct OpenÉire Studios to attend the Property and carry out the agreed photography, videography, drone, floor-plan and/or other property-media services. They confirm that OpenÉire Studios and its authorised personnel may enter and access the parts of the Property reasonably required to carry out the agreed Services, subject to any restrictions identified in this Authorisation. The person authorising access need not be the person paying OpenÉire. Authority extends only to the locations specified in this document, not unrelated properties."),
    ("Known hazards and site conditions", "Disclose known hazards, unusual site conditions and restricted areas relevant to the work, or select No known hazards to disclose. Examples include unstable floors or structures, derelict buildings, construction, exposed electrical hazards, machinery, livestock or animals, electric fencing, open water, steep or unstable ground, concealed holes, drains or trenches, hazardous substances and restricted access. OpenÉire may refuse to enter, remain in, operate equipment within, or capture media from any area that its personnel reasonably consider unsafe, unlawful or operationally unsuitable."),
    ("Property readiness", "So far as reasonably possible, the Property should be ready for the agreed shoot at the scheduled time. Unless specifically agreed in advance, OpenÉire is not normally responsible for cleaning, staging, moving heavy furniture, handling fragile or valuable possessions, restraining animals, moving/removing vehicles, maintenance or property preparation. Refer to the Booking Agreement for consequences of material delay, inaccessible areas or the property not being ready."),
    ("Specific requirements and professional judgement", "Where the Client has no particular preferences, they may select No specific requirements or state N/A. In that case, OpenÉire will use its professional judgement to capture and present the Property in accordance with the agreed package or written scope. No specific requirements means no additional shot-by-shot instructions were supplied. The Client is not expected to direct OpenÉire's normal photography/videography process. All agreed services and contractual deliverables remain fully intact: this does not waive or reduce the package, excuse genuine OpenÉire mistakes, or prevent reasonable requests during the Shoot or complaints about failure to deliver agreed work."),
    ("Essential / must-capture features", "The Client / Property Representative is responsible for identifying before or during the Shoot any specific feature, view, room, boundary, fencing, access point, structure, land parcel, selling feature, angle or other element that they consider essential to the marketing brief. Where the Client or their representative is present during the Shoot, OpenÉire may reasonably rely on their instructions regarding any specific required coverage. Requirements may relate to large acreage, multiple parcels, bog, forestry, lakeside land, agricultural areas, derelict buildings, development sites or geographically distinct capture points. Identify the relevant location for each requirement."),
    ("Video / social-media requirements", "Where video is included, specific video directions are optional; No specific video requirements or N/A is acceptable. Examples such as establishing shots, presenter positioning, transitions, views or intro/outro requirements are suggestions only, not additional deliverables. The Booking Agreement / agreed written scope remains the source of truth for whether video or social-media content is included."),
    ("On-site scope changes", "Raise material additional requests with OpenÉire before additional work is undertaken. OpenÉire may determine that a request is already within scope, can reasonably be accommodated during the current Shoot, or is additional chargeable work. Entering a request into this form does not automatically amend the agreed scope, quote or invoice. Any price change must follow the existing authorised quote/invoice adjustment process."),
    ("Requests after departure", "Once OpenÉire has left the Property, a request to photograph or film an element that was not previously identified as part of the agreed scope may be treated as additional work. Where fulfilling a newly introduced request requires another visit to the Property, additional attendance, travel, capture and/or production charges may apply. This does not apply where OpenÉire failed to capture an item that was expressly included in the agreed written scope. Selecting No specific requirements does not prevent a complaint about failure to deliver something objectively included in the agreed package or written scope."),
    ("Safety and operational discretion", "Capture may be affected by weather, aviation restrictions, privacy considerations, site safety, access, lighting, legal/regulatory restrictions or other operational factors. OpenÉire retains final operational discretion over whether a particular capture can be completed safely and lawfully. This requires a reasonable operational justification and is not an unlimited right to avoid agreed work."),
    ("Final on-site scope check", "Before leaving the Property, OpenÉire will ask whether any additional essential feature or area already identified as part of the agreed brief remains to be captured, where a representative is available. This is a reasonable opportunity to flag something important; the Client need not inspect every photograph or direct the entire shoot. Staff may record No outstanding agreed capture identified, Outstanding agreed capture noted, or No additional specific requirements identified. A second signature is not normally required."),
    ("Acceptance - choose either method", "By signing or otherwise formally accepting this Property Access & Shoot Authorisation, the person named below confirms that they have read and understood the form and that, to the best of their knowledge, the information provided is accurate. You may complete the secure page and type your name to accept electronically, or print, complete and sign the PDF and return it. Both methods are equally acceptable. Printing is optional; neither party is required to own a printer or to print on the other's behalf."),
]
