# Generated by Django 4.2.17 on 2026-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('client_type', models.CharField(choices=[('estate_agent', 'Estate Agent'), ('developer', 'Developer'), ('private_seller', 'Private Seller'), ('landlord', 'Landlord'), ('other', 'Other')], max_length=32)),
                ('property_address', models.TextField()),
                ('county', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('preferred_package', models.CharField(choices=[('essential', 'Essential'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium'), ('custom', 'Custom'), ('not_sure', 'Not Sure')], max_length=32)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('eircode', models.CharField(blank=True, max_length=20)),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('how_heard', models.CharField(blank=True, choices=[('google', 'Google'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('estate_agent_colleague', 'Estate Agent Colleague'), ('openeire_website', 'OpenEire Website'), ('other', 'Other'), ('not_sure', 'Not Sure')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('booked', 'Booked'), ('completed', 'Completed'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shoot_date', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
