# Generated by Django 4.2.17 on 2026-07-07 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0005_realestateenquiry_delivery_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enquiry_received', 'Enquiry received'), ('quote_sent', 'Quote sent'), ('booking_agreement_sent', 'Booking agreement sent'), ('booking_agreement_received', 'Booking agreement received'), ('deposit_request_sent', 'Deposit request sent'), ('deposit_paid', 'Deposit paid'), ('confirmation_sent', 'Confirmation sent'), ('weather_reschedule_sent', 'Weather reschedule sent'), ('shoot_scheduled', 'Shoot scheduled'), ('shoot_completed', 'Shoot completed'), ('delivery_sent', 'Delivery sent'), ('follow_up_sent', 'Follow-up sent'), ('thank_you_sent', 'Thank-you sent'), ('review_received', 'Review received'), ('status_changed', 'Status changed'), ('note', 'Note')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='completed', max_length=20)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('client', 'Client')], default='system', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('email_template', models.CharField(blank=True, max_length=100)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('reference_url', models.URLField(blank=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='realestate.realestateenquiry')),
            ],
            options={
                'verbose_name': 'Real estate timeline event',
                'verbose_name_plural': 'Real estate timeline events',
                'ordering': ['-created_at'],
            },
        ),
    ]
