# Generated by Django 4.2.17 on 2026-07-14 16:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0007_realestate_pricing_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateDeliveryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RealEstateDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt')], max_length=12)),
                ('year', models.PositiveSmallIntegerField()),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance'), ('full', 'Full'), ('adjustment', 'Adjustment')], max_length=20)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=20)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('customer_name_snapshot', models.CharField(max_length=255)),
                ('company_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('customer_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=50)),
                ('property_reference_snapshot', models.TextField()),
                ('job_reference_snapshot', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255)),
                ('stripe_invoice_url', models.URLField(blank=True, max_length=500)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_checkout_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='realestate.realestateenquiry')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='realestatetimelineevent',
            name='event_type',
            field=models.CharField(choices=[('enquiry_received', 'Enquiry received'), ('quote_sent', 'Quote sent'), ('booking_agreement_sent', 'Booking agreement sent'), ('booking_agreement_received', 'Booking agreement received'), ('deposit_request_sent', 'Deposit request sent'), ('deposit_paid', 'Deposit paid'), ('confirmation_sent', 'Confirmation sent'), ('weather_reschedule_sent', 'Weather reschedule sent'), ('shoot_scheduled', 'Shoot scheduled'), ('shoot_completed', 'Shoot completed'), ('delivery_sent', 'Delivery sent'), ('follow_up_sent', 'Follow-up sent'), ('thank_you_sent', 'Thank-you sent'), ('review_received', 'Review received'), ('status_changed', 'Status changed'), ('note', 'Note'), ('invoice_issued', 'Invoice issued'), ('payment_recorded', 'Payment recorded'), ('invoice_paid', 'Invoice paid in full'), ('delivery_ready', 'Delivery ready'), ('delivery_released', 'Delivery released'), ('delivery_override_granted', 'Delivery override granted'), ('delivery_override_revoked', 'Delivery override revoked')], max_length=50),
        ),
        migrations.CreateModel(
            name='RealEstatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('method', models.CharField(choices=[('stripe_deposit_checkout', 'Stripe deposit Checkout'), ('stripe_balance_checkout', 'Stripe balance Checkout'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded'), ('void', 'Void')], default='pending', max_length=24)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('cash_receipt_number', models.CharField(blank=True, max_length=20)),
                ('bank_lodgement_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='realestate.realestateinvoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='realestatedocumentsequence',
            constraint=models.UniqueConstraint(fields=('kind', 'year'), name='uniq_re_doc_sequence'),
        ),
        migrations.AddField(
            model_name='realestatedeliveryoverride',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realestate_delivery_overrides_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestatedeliveryoverride',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_overrides', to='realestate.realestateenquiry'),
        ),
        migrations.AddField(
            model_name='realestatedeliveryoverride',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_delivery_overrides_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='realestatepayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='re_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestatepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_checkout_session_id', ''), _negated=True), fields=('stripe_checkout_session_id',), name='uniq_re_payment_checkout_session'),
        ),
        migrations.AddConstraint(
            model_name='realestatepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id', ''), _negated=True), fields=('stripe_payment_intent_id',), name='uniq_re_payment_intent'),
        ),
        migrations.AddConstraint(
            model_name='realestatepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('cash_receipt_number', ''), _negated=True), fields=('cash_receipt_number',), name='uniq_re_cash_receipt'),
        ),
        migrations.AddConstraint(
            model_name='realestateinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'void'), _negated=True), fields=('enquiry', 'invoice_type'), name='uniq_active_re_invoice_type'),
        ),
        migrations.AddConstraint(
            model_name='realestateinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_checkout_session_id', ''), _negated=True), fields=('stripe_checkout_session_id',), name='uniq_re_invoice_checkout_session'),
        ),
        migrations.AddConstraint(
            model_name='realestatedeliveryoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('enquiry',), name='uniq_active_re_delivery_override'),
        ),
    ]
