# Generated by Django 4.2.17 on 2026-07-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_backfill_realestate_invoices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='realestateinvoice',
            name='uniq_active_re_invoice_type',
        ),
        migrations.AddConstraint(
            model_name='realestateinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'void'), _negated=True), ('invoice_type__in', ('deposit', 'balance', 'full'))), fields=('enquiry', 'invoice_type'), name='uniq_active_re_invoice_type'),
        ),
    ]
