# Generated by Django 4.2.17 on 2026-07-14 19:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0010_allow_multiple_adjustments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestateinvoice',
            old_name='stripe_invoice_url',
            new_name='stripe_hosted_invoice_url',
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='custom_payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='custom_required_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='expected_payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='payment_arrangement',
            field=models.CharField(choices=[('deposit_then_balance', '30% deposit then balance'), ('full_upfront', 'Full payment upfront'), ('full_on_shoot_day', 'Full payment on shoot day'), ('custom', 'Custom')], default='deposit_then_balance', max_length=24),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_invoice_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_invoice_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_invoice_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_invoice_pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_invoice_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_marked_paid_out_of_band_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_marked_paid_out_of_band_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_invoices_marked_paid_out_of_band', to=settings.AUTH_USER_MODEL),
        ),
    ]
