# Generated by Django 4.2.17 on 2026-07-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_payment_arrangements_stripe_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatepayment',
            name='method',
            field=models.CharField(choices=[('stripe_deposit_checkout', 'Stripe deposit Checkout'), ('stripe_balance_checkout', 'Stripe balance Checkout'), ('stripe_invoice', 'Stripe invoice'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], max_length=32),
        ),
    ]
