# Generated by Django 4.2.17 on 2026-07-14 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0012_stripe_invoice_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateBookingAgreementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.CharField(default='1.4', max_length=16)),
                ('payment_arrangement', models.CharField(max_length=24)),
                ('total_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('expected_payment_method', models.CharField(blank=True, max_length=20)),
                ('custom_payment_terms', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict)),
                ('rendered_markdown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_booking_agreement_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_agreement_snapshots', to='realestate.realestateenquiry')),
            ],
            options={
                'verbose_name': 'Real estate booking agreement snapshot',
                'verbose_name_plural': 'Real estate booking agreement snapshots',
                'ordering': ('-created_at',),
            },
        ),
    ]
