# Generated by Django 4.2.17 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_realestatebookingagreementsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatetimelineevent',
            name='reference_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
