# Generated by Django 4.2.17 on 2026-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_alter_realestatetimelineevent_reference_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateenquiry',
            name='stripe_deposit_creation_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
