# Generated by Django 4.2.17 on 2026-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0015_realestateenquiry_stripe_deposit_creation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatebookingagreementsnapshot',
            name='template_version',
            field=models.CharField(default='1.5', max_length=16),
        ),
    ]
