# Generated by Django 4.2.17 on 2026-07-20 12:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0016_alter_realestatebookingagreementsnapshot_template_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateenquiry',
            name='travel_details',
            field=models.TextField(blank=True, help_text='Explain the agreed travel basis, such as chargeable distance or destination. Required before issuing an agreement when the travel add-on is selected.'),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='travel_supplement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exact travel supplement already included in the quoted price. Required before issuing an agreement when the travel add-on is selected.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
