# Generated by Django 4.2.17 on 2026-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0017_realestateenquiry_travel_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateenquiry',
            name='access_contact',
            field=models.CharField(blank=True, help_text='Name and contact details for the person providing access on site.', max_length=255),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='access_notes',
            field=models.TextField(blank=True, help_text='Agreed access instructions, restrictions or arrival notes.'),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='shoot_time',
            field=models.TimeField(blank=True, help_text='Agreed local start time for the property shoot.', null=True),
        ),
    ]
