# Generated by Django 4.2.17 on 2026-07-24 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0019_alter_realestatebookingagreementsnapshot_template_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateenquiry',
            name='access_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='access_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='access_provider',
            field=models.CharField(blank=True, choices=[('enquirer', 'Enquirer'), ('owner', 'Property owner / vendor'), ('tenant', 'Tenant'), ('agent_colleague', 'Agent / colleague'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='additional_stills_quantity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Public requests are limited to 50 additional edited images.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='alternative_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='audio_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='bedroom_count',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6_plus', '6+'), ('not_applicable', 'Not applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='floor_count',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4_plus', '4+'), ('not_applicable', 'Not applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='grounds_size',
            field=models.CharField(blank=True, choices=[('no_grounds', 'No grounds'), ('normal_garden', 'Normal garden'), ('large_garden', 'Large garden'), ('under_1_acre', 'Under 1 acre'), ('1_to_5_acres', '1-5 acres'), ('over_5_acres', 'Over 5 acres'), ('not_sure', 'Not sure'), ('not_applicable', 'Not applicable')], max_length=24),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='internal_floor_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='internal_floor_area_unit',
            field=models.CharField(blank=True, choices=[('sqm', 'm²'), ('sqft', 'sq ft')], max_length=4),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='location_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='no_eircode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='occupancy_status',
            field=models.CharField(blank=True, choices=[('vacant', 'Vacant'), ('owner_occupied', 'Owner occupied'), ('tenant_occupied', 'Tenant occupied'), ('new_build_site', 'New build / site'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='on_camera',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], max_length=12),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='on_camera_people',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='outbuildings',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], max_length=12),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='outbuildings_details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='preferred_time_window',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('flexible', 'Flexible')], max_length=12),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='property_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='property_type_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='readiness_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='scheduling_preference',
            field=models.CharField(blank=True, choices=[('request_date', 'Request a preferred date'), ('flexible', 'Flexible / please contact me')], max_length=20),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='secondary_accommodation',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], max_length=12),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='secondary_accommodation_details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
