# Generated by Django 4.2.17 on 2026-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_realestateenquiry_access_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateenquiry',
            name='form_schema_version',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Public enquiry payload schema. Blank indicates the legacy form; version 2 uses the structured shoot-scoping form.', null=True),
        ),
    ]
