# Generated by Django 4.2.17 on 2026-07-28 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0023_alter_realestatebookingagreementsnapshot_template_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('photographs', 'Photographs'), ('main_video', 'Main video'), ('social_video', 'Social video'), ('floor_plan', 'Floor plan'), ('archive', 'ZIP / archive'), ('other', 'Other')], max_length=24)),
                ('display_name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('checksum_algorithm', models.CharField(blank=True, max_length=32)),
                ('checksum_value', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RealEstateDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_title', models.CharField(help_text='Use a privacy-safe title; do not include an exact address or Eircode.', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('portal_enabled', models.BooleanField(default=False, help_text='Selectively enables portal delivery when the global feature flag is on.')),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('licence_summary', models.TextField(blank=True)),
                ('download_instructions', models.TextField(blank=True)),
                ('feature_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_deliveries_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_delivery', to='realestate.realestateenquiry')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_deliveries_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('activate_realestatedelivery', 'Can activate real estate delivery'), ('revoke_realestatedelivery', 'Can revoke real estate delivery'), ('archive_realestatedelivery', 'Can archive real estate delivery')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateDeliveryRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('commissioning_client', 'Commissioning client'), ('agent', 'Agent'), ('vendor', 'Vendor'), ('payer', 'Payer'), ('other', 'Other')], max_length=24)),
                ('token_salt', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('token_created_at', models.DateTimeField(auto_now_add=True)),
                ('token_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('first_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('first_download_url_issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='realestate.realestatedelivery')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_delivery_recipients_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'email'),
                'permissions': [('rotate_realestatedeliveryrecipient', 'Can rotate recipient delivery link'), ('revoke_realestatedeliveryrecipient', 'Can revoke delivery recipient')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateDeliveryEmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initial', 'Initial'), ('resend', 'Resend'), ('expiry_reminder', 'Expiry reminder'), ('extension', 'Extension'), ('replacement', 'Replacement')], max_length=24)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('content_version', models.CharField(default='1', max_length=32)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_attempts', to='realestate.realestatedeliveryrecipient')),
            ],
            options={
                'ordering': ('-attempted_at',),
            },
        ),
        migrations.CreateModel(
            name='RealEstateDeliveryAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_accessed', 'Page/session accessed'), ('download_url_issued', 'Download URL issued'), ('access_denied', 'Access denied'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('upload_completed', 'Upload completed'), ('file_replaced', 'File replaced'), ('cleanup_succeeded', 'Cleanup succeeded'), ('cleanup_failed', 'Cleanup failed')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='realestate.realestatedeliverable')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='realestate.realestatedelivery')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='realestate.realestatedeliveryrecipient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='realestatedeliverable',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='realestate.realestatedelivery'),
        ),
        migrations.AddField(
            model_name='realestatedeliverable',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='realestate.realestatedeliverable'),
        ),
        migrations.AddField(
            model_name='realestatedeliverable',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_deliverables_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RealEstateDeliveryUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('photographs', 'Photographs'), ('main_video', 'Main video'), ('social_video', 'Social video'), ('floor_plan', 'Floor plan'), ('archive', 'ZIP / archive'), ('other', 'Other')], max_length=24)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('upload_id', models.CharField(max_length=1024, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completing', 'Completing'), ('completed', 'Completed'), ('aborting', 'Aborting'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='initiated', max_length=16)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('expected_mime_type', models.CharField(max_length=100)),
                ('part_size', models.PositiveBigIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('aborted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_delivery_upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='realestate.realestatedelivery')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_upload_sessions', to='realestate.realestatedeliverable')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_by', 'status'], name='redelupl_creator_status_idx'), models.Index(fields=['delivery', 'status'], name='redelupl_delivery_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='realestatedeliveryrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('delivery', 'email'), name='uniq_active_re_delivery_recipient_email'),
        ),
        migrations.AddConstraint(
            model_name='realestatedeliveryrecipient',
            constraint=models.CheckConstraint(check=models.Q(('token_version__gt', 0)), name='re_delivery_recipient_token_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestatedeliverable',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gt', 0)), name='re_deliverable_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestatedeliverable',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='re_deliverable_version_positive'),
        ),
    ]
