# Generated by Django 4.2.17 on 2026-07-28 18:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0024_realestatedeliverable_realestatedelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatepayment',
            name='reversal_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='realestatepayment',
            name='reversal_status',
            field=models.CharField(choices=[('none', 'None'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('chargeback', 'Chargeback')], default='none', max_length=24),
        ),
        migrations.AddField(
            model_name='realestatepayment',
            name='reversed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='realestatepayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='realestatepayment',
            constraint=models.CheckConstraint(check=models.Q(('reversed_amount__gte', 0)), name='re_payment_reversed_amount_nonnegative'),
        ),
    ]
