# Generated by Django 4.2.17 on 2026-07-28 18:16

from django.db import migrations, models
import uuid


def populate_delivery_public_ids(apps, schema_editor):
    delivery_model = apps.get_model("realestate", "RealEstateDelivery")
    for delivery in delivery_model.objects.filter(public_id__isnull=True).iterator():
        delivery.public_id = uuid.uuid4()
        delivery.save(update_fields=("public_id",))


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0025_realestatepayment_reversal_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatedelivery',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_delivery_public_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='realestatedelivery',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
