# Generated by Django 4.2.17 on 2026-07-28 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0025_realestatepayment_reversal_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatedelivery',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
