# Generated by Django 4.2.17 on 2026-08-04 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0026_realestatedelivery_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateBookingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('token_salt', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_exchanged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('generate_realestatebookingcredential', 'Can generate real estate booking credentials'), ('rotate_realestatebookingcredential', 'Can rotate real estate booking credentials'), ('revoke_realestatebookingcredential', 'Can revoke real estate booking credentials')],
            },
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='contact_details_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='contact_update_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='contact_update_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='submission_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='submission_source',
            field=models.CharField(choices=[('public_form', 'Public form'), ('returning_client', 'Returning client'), ('whatsapp_manual', 'WhatsApp / manual'), ('django_admin', 'Django admin'), ('legacy_unknown', 'Legacy / unknown')], default='legacy_unknown', max_length=24),
        ),
        migrations.CreateModel(
            name='RealEstateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('normalized_email', models.EmailField(blank=True, db_index=True, editable=False, max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=32)),
                ('client_type', models.CharField(choices=[('estate_agent', 'Estate Agent'), ('developer', 'Developer'), ('private_seller', 'Private Seller'), ('landlord', 'Landlord'), ('other', 'Other')], max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('identity_confirmed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realestate_clients_confirmed', to=settings.AUTH_USER_MODEL)),
                ('source_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created_from_enquiry', to='realestate.realestateenquiry')),
            ],
            options={
                'ordering': ('name', 'company_name'),
                'permissions': [('resolve_realestateclient', 'Can resolve real estate client identity')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateBookingEmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initial', 'Initial'), ('resend', 'Resend')], max_length=12)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('content_version', models.CharField(default='1', max_length=16)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_attempts', to='realestate.realestatebookingcredential')),
            ],
            options={
                'ordering': ('-attempted_at',),
            },
        ),
        migrations.AddField(
            model_name='realestatebookingcredential',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_credentials', to='realestate.realestateclient'),
        ),
        migrations.AddField(
            model_name='realestatebookingcredential',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realestate_booking_credentials_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestatebookingcredential',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_booking_credentials_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestatebookingcredential',
            name='rotated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_booking_credentials_rotated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RealEstateBookingAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('exchange', 'Credential exchange'), ('session', 'Session accessed'), ('submission', 'Booking submitted'), ('access_denied', 'Access denied'), ('rotated', 'Credential rotated'), ('revoked', 'Credential revoked'), ('email_sent', 'Booking link email sent')], max_length=24)),
                ('result_code', models.CharField(choices=[('allowed', 'Allowed'), ('submitted', 'Submitted'), ('duplicate', 'Duplicate submission'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('client_inactive', 'Client inactive'), ('invalid_session', 'Invalid session'), ('rotated', 'Rotated'), ('email_accepted', 'Email accepted')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_access_events', to='realestate.realestateclient')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='realestate.realestatebookingcredential')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_access_events', to='realestate.realestateenquiry')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='realestate.realestateclient'),
        ),
        migrations.AddField(
            model_name='realestateenquiry',
            name='returning_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='realestate.realestatebookingcredential'),
        ),
        migrations.AddConstraint(
            model_name='realestatebookingcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('revoked_at__isnull', True)), fields=('client',), name='uniq_active_primary_re_booking_credential'),
        ),
        migrations.AddConstraint(
            model_name='realestatebookingcredential',
            constraint=models.CheckConstraint(check=models.Q(('token_version__gt', 0)), name='re_booking_credential_version_positive'),
        ),
    ]
