# Generated by Django 4.2.17 on 2026-08-24 17:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0027_widen_stripe_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateinvoice',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='realestate.realestateinvoice'),
        ),
        migrations.CreateModel(
            name='RealEstateFinancialAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('goodwill_credit', 'Goodwill credit'), ('negotiated_discount', 'Negotiated discount'), ('pricing_correction', 'Pricing correction')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('customer_description', models.CharField(max_length=255)),
                ('internal_reason', models.TextField()),
                ('request_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realestate_financial_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments', to='realestate.realestateenquiry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestate_financial_adjustments_reversed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': (('apply_financial_adjustment', 'Can apply financial adjustment'), ('reverse_financial_adjustment', 'Can reverse financial adjustment')),
            },
        ),
        migrations.AddConstraint(
            model_name='realestatefinancialadjustment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='re_financial_adjustment_amount_positive'),
        ),
    ]
