# Generated by Django 4.2.17 on 2026-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0029_alter_realestatebookingagreementsnapshot_template_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateenquiry',
            name='agreed_scope',
            field=models.TextField(blank=True, help_text='Approved deliverables, one per line. Required for Custom work; optional replacement for standard package scope. Customer requests/internal notes are not approved scope. Changes apply only to newly issued agreements.'),
        ),
    ]
