# Generated by Django 4.2.17 on 2026-09-11 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import realestate.authorisation_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0030_realestateenquiry_agreed_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyScopeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('person_confirming', models.CharField(help_text='Name, or explicitly record that no representative was present/available.', max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('complete', 'No outstanding agreed capture identified'), ('outstanding', 'Outstanding agreed capture noted'), ('no_specific', 'No additional specific requirements identified')], max_length=20)),
                ('all_agreed_completed', models.BooleanField(default=True)),
                ('outstanding_capture', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_scope_checks', to='realestate.realestateenquiry')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PropertyAuthorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(help_text='Exact property, parcel or locations covered by this authorisation only.')),
                ('template_version', models.CharField(default='1.0', editable=False, max_length=16)),
                ('token', models.CharField(default=realestate.authorisation_models.authorisation_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent / awaiting authorisation'), ('electronic', 'Accepted electronically'), ('handwritten', 'Handwritten copy received')], default='draft', max_length=16)),
                ('issued_snapshot', models.JSONField(default=dict, editable=False)),
                ('accepted_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('issued_pdf', models.BinaryField()),
                ('accepted_pdf', models.BinaryField(null=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_name', models.CharField(blank=True, max_length=255)),
                ('accepted_capacity', models.CharField(blank=True, max_length=255)),
                ('accepted_email', models.EmailField(blank=True, max_length=254)),
                ('acceptance_method', models.CharField(blank=True, choices=[('electronic', 'Electronic'), ('handwritten', 'Handwritten')], max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_authorisations_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_authorisations', to='realestate.realestateenquiry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_authorisations_recorded', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='realestate.propertyauthorisation')),
            ],
            options={
                'verbose_name': 'Property access & shoot authorisation',
                'ordering': ('-created_at',),
            },
        ),
    ]
