# Generated by Django 4.2.17 on 2026-09-13 15:25

from django.db import migrations, models


def flag_legacy_invoices(apps, schema_editor):
    Invoice = apps.get_model("realestate", "RealEstateInvoice")
    invoices = Invoice.objects.using(schema_editor.connection.alias)
    # The old implementation could forget a successful remote POST. Blank IDs
    # on existing issued/void/paid rows are not evidence of no Stripe activity.
    invoices.filter(stripe_invoice_id="").exclude(status="draft").update(
        stripe_sync_state="recovery_required",
        stripe_sync_data={"recovery_reason": "Pre-migration Stripe creation history is unknown; reconcile before reuse."},
    )
    invoices.exclude(stripe_invoice_id="").update(
        stripe_sync_state="legacy_remote", stripe_sync_data={"legacy": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0031_propertyscopecheck_propertyauthorisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_sync_data',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_sync_lock_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_sync_lock_until',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvoice',
            name='stripe_sync_state',
            field=models.CharField(choices=[('never', 'Stripe never attempted'), ('customer_pending', 'Customer creation pending / outcome unknown'), ('create_pending', 'Invoice creation pending / outcome unknown'), ('item_pending', 'Stripe invoice created; line item pending'), ('finalize_pending', 'Finalisation pending / failed'), ('finalized', 'Finalised; send not confirmed'), ('send_pending', 'Send pending / outcome unknown'), ('sent', 'Sent'), ('recovery_required', 'Recovery required — review Stripe before proceeding'), ('void_confirmed', 'Stripe void confirmed'), ('legacy_remote', 'Stripe invoice exists; historical send outcome unknown')], default='never', editable=False, max_length=24),
        ),
        migrations.RunPython(flag_legacy_invoices, migrations.RunPython.noop),
    ]
