# Generated by Django 4.2.17 on 2026-02-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_country_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('countries', models.JSONField(default=list, help_text="List of Country Codes, e.g. ['IE', 'US']")),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('standard', 'Standard (Rolled Tube)'), ('large', 'Large (Wide Tube)'), ('giant', 'Giant/Panoramic (Oversize)'), ('bulky', 'Eco Canvas (Box)')], max_length=20)),
                ('method', models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('express', 'Express')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Shipping cost to charge customer', max_digits=6)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='checkout.shippingzone')),
            ],
            options={
                'unique_together': {('zone', 'tier', 'method')},
            },
        ),
    ]
