# Generated by Django 4.2.17 on 2026-02-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_printtemplate_options_and_more'),
        ('checkout', '0003_shippingzone_shippingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IE', 'Ireland'), ('US', 'United States')], max_length=2)),
                ('method', models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('express', 'Express')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to='products.printtemplate')),
            ],
            options={
                'unique_together': {('product', 'country', 'method')},
            },
        ),
        migrations.DeleteModel(
            name='ShippingRate',
        ),
        migrations.DeleteModel(
            name='ShippingZone',
        ),
    ]
