# Generated by Django 4.2.17 on 2026-02-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_productshipping_delete_shippingrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('express', 'Express')], default='budget', help_text='The shipping speed selected by the customer', max_length=20),
        ),
    ]
