# Generated by Django 4.2.17 on 2026-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='personal_terms_version',
            field=models.CharField(blank=True, help_text='Personal terms version captured for consumer digital downloads.', max_length=80, null=True),
        ),
    ]
