# Generated by Django 5.2.6 on 2026-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0008_order_confirmation_email_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prodigi_last_polled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
