# Generated by Django 5.2.6 on 2026-06-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0009_order_prodigi_last_polled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("normalized_email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=50)),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="discount_redemption", to="checkout.order"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="discountredemption",
            constraint=models.UniqueConstraint(fields=("normalized_email", "code"), name="uniq_discount_redemption_email_code"),
        ),
    ]
