# Generated by Django 5.2.6 on 2026-06-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_newslettersubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="brevo_sync_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="brevo_sync_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="brevo_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
