# Generated by Django 4.2.17 on 2026-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_alter_userprofile_default_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
