from django.urls import path
from .views import (
    AILicenseDraftUpdateView,
    AILicenseDraftQueueView,
    GalleryListView,
    DigitalPhotoDetailView,
    PhysicalPhotoDetailView,
    VideoDetailView,
    ProductDetailView,
    ProductReviewListCreateView,
    RequestGalleryAccessView,
    VerifyGalleryAccessView,
    ShoppingBagRecommendationsView,
    PersonalUseLicenceTextView,
    PersonalLicenceDownloadView,
    ProtectedDownloadView,
    LicenceAssetDownloadView,
    PersonalAssetDownloadView,
    LicenseRequestCreateView
)
from .upload_views import (
    AbortVideoMultipartUploadView,
    CompleteVideoMultipartUploadView,
    StaffVideoTargetListView,
    StartVideoMultipartUploadView,
    VideoMultipartPartUrlView,
)

urlpatterns = [
    path('uploads/videos/targets/', StaffVideoTargetListView.as_view(), name='video-upload-targets'),
    path('uploads/videos/start/', StartVideoMultipartUploadView.as_view(), name='video-upload-start'),
    path('uploads/videos/part-url/', VideoMultipartPartUrlView.as_view(), name='video-upload-part-url'),
    path('uploads/videos/complete/', CompleteVideoMultipartUploadView.as_view(), name='video-upload-complete'),
    path('uploads/videos/abort/', AbortVideoMultipartUploadView.as_view(), name='video-upload-abort'),
    path('licence/personal-use/', PersonalUseLicenceTextView.as_view(), name='personal-licence-text'),
    path('licence/personal-download/<uuid:token>/', PersonalLicenceDownloadView.as_view(), name='personal-licence-download'),
    path('products/download/<str:product_type>/<int:product_id>/', ProtectedDownloadView.as_view(), name='secure-download'),
    path('license/download/<uuid:token>/', LicenceAssetDownloadView.as_view(), name='license-asset-download'),
    path('personal-download/<uuid:token>/', PersonalAssetDownloadView.as_view(), name='personal-asset-download'),
    path('products/recommendations/', ShoppingBagRecommendationsView.as_view(), name='bag-recommendations'),
    path('gallery-request/', RequestGalleryAccessView.as_view(), name='gallery_request'),
    path('gallery-verify/', VerifyGalleryAccessView.as_view(), name='gallery_verify'),
    path('gallery/', GalleryListView.as_view(), name='gallery_list'),
    path('photos/<int:pk>/', DigitalPhotoDetailView.as_view(), name='photo_detail'),
    path('videos/<int:pk>/', VideoDetailView.as_view(), name='video_detail'),
    path('products/<int:pk>/', PhysicalPhotoDetailView.as_view(), name='physical_product_page'),
    path('variants/<int:pk>/', ProductDetailView.as_view(), name='variant_detail'),
    path('<str:product_type>/<int:pk>/reviews/', ProductReviewListCreateView.as_view(), name='review_list_create'),
    path('license-requests/', LicenseRequestCreateView.as_view(), name='license-request-create'),
    path('internal/draft-queue/', AILicenseDraftQueueView.as_view(), name='ai-draft-queue'),
    path('internal/draft-update/<int:pk>/', AILicenseDraftUpdateView.as_view(), name='ai-draft-update'),
]
