# Generated by Django 5.2.6 on 2025-09-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(upload_to='previews/photos/')),
                ('high_res_file', models.FileField(upload_to='digital_products/photos/')),
                ('price_hd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_4k', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tags', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('thumbnail_image', models.ImageField(upload_to='previews/videos/')),
                ('video_file', models.FileField(upload_to='digital_products/videos/')),
                ('price_hd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_4k', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tags', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('canvas', 'Canvas'), ('framed', 'Framed Print')], max_length=10)),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='products.photo')),
            ],
        ),
    ]
