# Generated by Django 5.2.6 on 2025-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='collection',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='collection',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
