# Generated by Django 4.2.17 on 2025-12-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('matte', 'Fine Art Print (Matte)'), ('gloss', 'Fine Art Print (Gloss)'), ('canvas', 'Premium Canvas'), ('framed', 'Framed Fine Art Print')], max_length=20)),
                ('size', models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('A3', 'A3 (297x420mm)'), ('A2', 'A2 (420x594mm)'), ('12x16', '12x16"'), ('16x20', '16x20"'), ('18x24', '18x24"'), ('24x36', '24x36"')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.CharField(blank=True, help_text='Prodigi SKU (e.g. GLOBAL-CAN-12x16)', max_length=254, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.photo')),
            ],
            options={
                'ordering': ['material', 'size'],
                'unique_together': {('photo', 'material', 'size')},
            },
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('content_type', 'object_id', 'user')},
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
