# Generated by Django 4.2.17 on 2025-12-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('matte', 'Fine Art Print (Matte)'), ('gloss', 'Fine Art Print (Gloss)'), ('canvas', 'Premium Canvas'), ('framed', 'Framed Fine Art Print')], max_length=20)),
                ('size', models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('A3', 'A3 (297x420mm)'), ('A2', 'A2 (420x594mm)'), ('12x16', '12x16"'), ('16x20', '16x20"'), ('18x24', '18x24"'), ('24x36', '24x36"')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Default price for this size/material', max_digits=6)),
                ('sku_suffix', models.CharField(help_text="e.g. 'CAN-A4' -> Result: 'PHOTO-ID-CAN-A4'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['material', 'size'],
                'unique_together': {('material', 'size')},
            },
        ),
    ]
