# Generated by Django 4.2.17 on 2026-01-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_printtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='prodigi_shipping_method',
            field=models.CharField(default='Budget', help_text='Shipping tier (Budget, Standard, Express)', max_length=50),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='prodigi_sku',
            field=models.CharField(blank=True, help_text="Prodigi Product Code (e.g. 'GLOBAL-CAN-A4')", max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='prodigi_sku',
            field=models.CharField(blank=True, help_text='Prodigi SKU (e.g. GLOBAL-CAN-A4)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Default price', max_digits=6),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='sku_suffix',
            field=models.CharField(help_text="Internal Suffix e.g. 'CAN-A4'", max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Internal SKU (e.g. PHOTO-1-CAN-A4)', max_length=254, null=True),
        ),
    ]
