# Generated by Django 4.2.17 on 2026-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_printtemplate_prodigi_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printtemplate',
            name='material',
            field=models.CharField(choices=[('matte', 'Fine Art Paper (Matte)'), ('c-type', 'C-Type Silver Halide'), ('canvas', 'Eco Canvas'), ('etching', 'Hahnemuhle German Etching'), ('photo-rag', 'Hahnemuhle Photo Rag'), ('lustre', 'Photo Art Lustre Paper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='material',
            field=models.CharField(choices=[('matte', 'Fine Art Paper (Matte)'), ('c-type', 'C-Type Silver Halide'), ('canvas', 'Eco Canvas'), ('etching', 'Hahnemuhle German Etching'), ('photo-rag', 'Hahnemuhle Photo Rag'), ('lustre', 'Photo Art Lustre Paper')], max_length=20),
        ),
    ]
