# Generated by Django 4.2.17 on 2026-01-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_galleryaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_rate',
            field=models.CharField(blank=True, help_text='e.g. 24fps, 60fps', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, help_text='e.g. 3840x2160 (4K)', max_length=50, null=True),
        ),
    ]
