# Generated by Django 4.2.17 on 2026-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_video_duration_video_frame_rate_video_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
