# Generated by Django 4.2.17 on 2026-02-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productreview_admin_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='collection',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='collection',
            field=models.CharField(max_length=100),
        ),
    ]
