# Generated by Django 4.2.17 on 2026-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_photo_collection_alter_video_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printtemplate',
            name='prodigi_shipping_method',
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='shipping_tier',
            field=models.CharField(choices=[('standard', 'Standard (Rolled Tube)'), ('large', 'Large (Wide Tube)'), ('giant', 'Giant/Panoramic (Oversize)'), ('bulky', 'Eco Canvas (Box)')], default='standard', help_text='Determines which shipping cost rule applies', max_length=20),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Default retail price', max_digits=6),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='material',
            field=models.CharField(choices=[('canvas', 'Eco Canvas'), ('lustre', 'Lustre Photo Paper'), ('matte', 'Enhanced Matte Art Paper'), ('photo-rag', 'Hahnemuhle Photo Rag')], max_length=20),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='prodigi_sku',
            field=models.CharField(blank=True, help_text="Prodigi Product Code (e.g. 'GLOBAL-CAN-20x30')", max_length=50),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='size',
            field=models.CharField(choices=[('12x18', '12x18" (30x45cm)'), ('16x24', '16x24" (40x60cm)'), ('20x30', '20x30" (50x75cm)'), ('18x30', '18x30" (46x76cm)'), ('24x36', '24x36" (60x90cm)'), ('26x38', '26x38" (66x96cm)'), ('13x60', '13x60" (33x152cm)'), ('72x24', '72x24" (183x61cm)'), ('24x35', '24x35" (60x89cm)'), ('28x41', '28x41" (71x104cm)'), ('16x32', '16x32" (40x80cm)'), ('24x39', '24x39" (60x99cm)'), ('24x40', '24x40" (60x100cm)'), ('28x40', '28x40" (70x100cm)'), ('42x56', '42x56" (107x142cm)'), ('60x48', '60x48" (152x122cm)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='sku_suffix',
            field=models.CharField(help_text="Internal Suffix e.g. 'CAN-20x30'", max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='material',
            field=models.CharField(choices=[('canvas', 'Eco Canvas'), ('lustre', 'Lustre Photo Paper'), ('matte', 'Enhanced Matte Art Paper'), ('photo-rag', 'Hahnemuhle Photo Rag')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('12x18', '12x18" (30x45cm)'), ('16x24', '16x24" (40x60cm)'), ('20x30', '20x30" (50x75cm)'), ('18x30', '18x30" (46x76cm)'), ('24x36', '24x36" (60x90cm)'), ('26x38', '26x38" (66x96cm)'), ('13x60', '13x60" (33x152cm)'), ('72x24', '72x24" (183x61cm)'), ('24x35', '24x35" (60x89cm)'), ('28x41', '28x41" (71x104cm)'), ('16x32', '16x32" (40x80cm)'), ('24x39', '24x39" (60x99cm)'), ('24x40', '24x40" (60x100cm)'), ('28x40', '28x40" (70x100cm)'), ('42x56', '42x56" (107x142cm)'), ('60x48', '60x48" (152x122cm)')], max_length=20),
        ),
    ]
