# Generated by Django 4.2.17 on 2026-02-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_printtemplate_prodigi_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printtemplate',
            options={},
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='prodigi_sku',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='shipping_tier',
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost to produce (Item Price)', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='material',
            field=models.CharField(choices=[('eco_canvas', 'Eco Canvas'), ('lustre_photo_paper', 'Lustre Photo Paper'), ('enhanced_matte_art_paper', 'Enhanced Matte Art Paper'), ('hahnemuhle_photo_rag', 'Hahnemuhle Photo Rag')], max_length=50),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='size',
            field=models.CharField(choices=[('12x18', '12x18" (30x45cm)'), ('16x24', '16x24" (40x60cm)'), ('20x30', '20x30" (50x75cm)'), ('24x36', '24x36" (60x90cm)'), ('26x38', '26x38" (66x96cm)'), ('13x60', '13x60" (33x152cm)'), ('72x24', '72x24" (183x61cm)'), ('27x41', '27x41" (70x105cm)'), ('18x30', '18x30" (46x76cm)'), ('42x56', '42x56" (107x142cm)'), ('60x48', '60x48" (152x122cm)'), ('16x32', '16x32" (40x80cm)'), ('24x40', '24x40" (60x100cm)'), ('28x40', '28x40" (70x100cm)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='sku_suffix',
            field=models.CharField(max_length=50),
        ),
    ]
