# Generated by Django 4.2.17 on 2026-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_printtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='prodigi_sku',
            field=models.CharField(blank=True, help_text='Prodigi Product Code', max_length=50, null=True),
        ),
    ]
