# Generated by Django 4.2.17 on 2026-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_printtemplate_prodigi_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('12x18', '12x18" (30x45cm)'), ('16x24', '16x24" (40x60cm)'), ('20x30', '20x30" (50x75cm)'), ('24x36', '24x36" (60x90cm)'), ('26x38', '26x38" (66x96cm)'), ('13x60', '13x60" (33x152cm)'), ('72x24', '72x24" (183x61cm)'), ('27x41', '27x41" (70x105cm)'), ('18x30', '18x30" (46x76cm)'), ('42x56', '42x56" (107x142cm)'), ('60x48', '60x48" (152x122cm)'), ('16x32', '16x32" (40x80cm)'), ('24x40', '24x40" (60x100cm)'), ('28x40', '28x40" (70x100cm)')], max_length=20),
        ),
    ]
