# Generated by Django 4.2.17 on 2026-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='material',
            field=models.CharField(choices=[('eco_canvas', 'Eco Canvas'), ('lustre_photo_paper', 'Lustre Photo Paper'), ('enhanced_matte_art_paper', 'Enhanced Matte Art Paper'), ('hahnemuhle_photo_rag', 'Hahnemuhle Photo Rag')], max_length=30),
        ),
    ]
