# Generated by Django 4.2.17 on 2026-02-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0016_alter_productvariant_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LicenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('REAL_ESTATE', 'Real Estate / Property'), ('EDITORIAL', 'Editorial / Documentary'), ('COMMERCIAL', 'Commercial / Advertising'), ('OTHER', 'Other')], max_length=50)),
                ('duration', models.CharField(choices=[('1_YEAR', '1 Year'), ('2_YEARS', '2 Years'), ('PERPETUAL', 'Perpetual / Lifetime'), ('OTHER', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_draft_response', models.TextField(blank=True, help_text='AI generated draft response', null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_payment_link', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('photo', 'video')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
