# Generated by Django 4.2.17 on 2026-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0017_license_request_and_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'License Request', 'verbose_name_plural': 'License Requests'},
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='object_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='licenserequest',
            unique_together={('content_type', 'object_id', 'email')},
        ),
        migrations.AddIndex(
            model_name='licenserequest',
            index=models.Index(fields=['content_type', 'object_id'], name='license_asset_idx'),
        ),
    ]
