# Generated by Django 4.2.17 on 2026-02-26 19:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_licenserequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserequest',
            name='ai_draft_response',
            field=models.TextField(blank=True, help_text='AI generated draft response', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
