# Generated by Django 4.2.17 on 2026-03-01 17:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_licenserequest_ai_draft_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='high_res_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\godde\\Documents\\Miss Bott\\Projects\\OpenEire Studios\\openeire-api\\media'), upload_to='digital_products/photos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\godde\\Documents\\Miss Bott\\Projects\\OpenEire Studios\\openeire-api\\media'), upload_to='digital_products/videos/'),
        ),
    ]
