# Generated by Django 4.2.17 on 2026-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_photo_high_res_file_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='stripe_payment_link_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
