# Generated by Django 4.2.17 on 2026-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_licenserequest_stripe_payment_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='exclusivity',
            field=models.CharField(blank=True, choices=[('NON_EXCLUSIVE', 'Non-Exclusive'), ('CATEGORY', 'Category Exclusive'), ('FULL', 'Fully Exclusive')], default='NON_EXCLUSIVE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='permitted_media',
            field=models.CharField(blank=True, choices=[('WEB_SOCIAL', 'Web & Organic Social Only'), ('PAID_DIGITAL', 'Paid Digital Ads'), ('PRINT_BROCHURE', 'Print & Brochure'), ('BROADCAST', 'TV / Broadcast / Cinema'), ('ALL_MEDIA', 'All Media')], default='WEB_SOCIAL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='reach_caps',
            field=models.CharField(blank=True, default='NONE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='territory',
            field=models.CharField(blank=True, choices=[('IRELAND', 'Ireland Only'), ('EU', 'EU / UK'), ('US_NA', 'US / North America'), ('SOUTH_AMERICA', 'South America'), ('ASIA', 'Asia'), ('AFRICA', 'Africa'), ('OCEANIA', 'Oceania'), ('WORLDWIDE', 'Worldwide')], default='IRELAND', max_length=20, null=True),
        ),
    ]
