# Generated by Django 4.2.17 on 2026-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_licenserequest_exclusivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserequest',
            name='duration',
            field=models.CharField(choices=[('1_MONTH', '1 Month'), ('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEARS', '2 Years'), ('5_YEARS', '5 Years'), ('PERPETUAL', 'Perpetual / Lifetime'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='project_type',
            field=models.CharField(choices=[('REAL_ESTATE', 'Real Estate / Property'), ('CORPORATE', 'Corporate / B2B'), ('EDITORIAL', 'Editorial / Documentary'), ('COMMERCIAL', 'Commercial / Advertising'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
