# Generated by Django 4.2.17 on 2026-03-04 17:45

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_licenserequest_duration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenserequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='licenserequest',
            constraint=models.UniqueConstraint(
                fields=('content_type', 'object_id', 'email'),
                condition=~Q(status='REJECTED'),
                name='uniq_license_request_active',
            ),
        ),
    ]
