# Generated by Django 4.2.17 on 2026-03-04 18:05

from collections import defaultdict

from django.db import migrations, models
from django.db.models import F, Q
from django.db.models.functions import Lower


def normalize_emails(apps, schema_editor):
    LicenseRequest = apps.get_model('products', 'LicenseRequest')

    duplicates = defaultdict(list)
    for row in LicenseRequest.objects.all().values(
        'id', 'email', 'content_type_id', 'object_id', 'status'
    ):
        email = row['email'] or ''
        normalized = email.strip().lower()
        if row['status'] != 'REJECTED':
            key = (row['content_type_id'], row['object_id'], normalized)
            duplicates[key].append(row['id'])

    conflicting = [ids for ids in duplicates.values() if len(ids) > 1]
    if conflicting:
        sample = conflicting[0][:5]
        raise RuntimeError(
            "Found duplicate active LicenseRequest emails after normalization. "
            f"Resolve these IDs before migrating: {sample}"
        )

    for row in LicenseRequest.objects.all().values('id', 'email'):
        email = row['email']
        if email is None:
            continue
        normalized = email.strip().lower()
        if normalized != email:
            LicenseRequest.objects.filter(id=row['id']).update(email=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_license_request_active_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenserequest',
            name='uniq_license_request_active',
        ),
        migrations.RunPython(normalize_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='licenserequest',
            constraint=models.UniqueConstraint(
                Lower('email'),
                F('content_type'),
                F('object_id'),
                condition=~Q(status='REJECTED'),
                name='uniq_license_request_active_ci',
            ),
        ),
    ]
