# Generated by Django 4.2.17 on 2026-03-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_license_fulfilment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
