# Generated by Django 4.2.17 on 2026-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_licenserequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
