# Generated by Django 4.2.17 on 2026-03-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


def map_legacy_statuses(apps, schema_editor):
    LicenseRequest = apps.get_model('products', 'LicenseRequest')
    mapping = {
        'NEW': 'SUBMITTED',
        'REVIEWED': 'SUBMITTED',
        'QUOTED': 'PAYMENT_PENDING',
    }
    for old_status, new_status in mapping.items():
        LicenseRequest.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0028_alter_stripewebhookevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('scope_snapshot', models.JSONField(blank=True, default=dict)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('terms_version', models.CharField(max_length=50)),
                ('master_agreement_version', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_link_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_link_url', models.URLField(blank=True, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Request Audit Log',
                'verbose_name_plural': 'License Request Audit Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='licenserequest',
            name='uniq_license_request_active_ci',
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.RunPython(map_legacy_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='licenserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='licenserequest',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('content_type'), models.F('object_id'), condition=models.Q(('status__in', ['REJECTED', 'REVOKED', 'EXPIRED']), _negated=True), name='uniq_license_request_active_ci'),
        ),
        migrations.AddField(
            model_name='licenserequestauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenserequestauditlog',
            name='license_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.licenserequest'),
        ),
        migrations.AddField(
            model_name='licenceoffer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenceoffer',
            name='license_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.licenserequest'),
        ),
        migrations.AddConstraint(
            model_name='licenceoffer',
            constraint=models.UniqueConstraint(fields=('license_request', 'version'), name='uniq_licence_offer_version'),
        ),
    ]
