# Generated by Django 4.2.17 on 2026-04-13 20:02

from django.db import migrations, models
import products.storage


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_personaldownloadtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_key',
            field=models.CharField(blank=True, help_text='Existing private R2 object key, e.g. digital_products/videos/my-video.mp4', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, storage=products.storage.PrivateAssetStorage(), upload_to='digital_products/videos/'),
        ),
    ]
