# Generated by Django 4.2.17 on 2026-04-14 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0034_video_video_file_key_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_video_key',
            field=models.CharField(blank=True, help_text='Public preview clip object key, e.g. previews/videos/my-video-preview.mp4', max_length=500),
        ),
        migrations.CreateModel(
            name='VideoUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('upload_id', models.CharField(max_length=255, unique=True)),
                ('purpose', models.CharField(choices=[('master', 'Master'), ('preview', 'Preview')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('file_size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('part_size', models.PositiveBigIntegerField()),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('aborted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('target_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='products.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'status'], name='vidupl_creator_status_idx'), models.Index(fields=['purpose', 'status'], name='vidupl_purpose_status_idx')],
            },
        ),
    ]
