# Generated by Django 4.2.17 on 2026-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_video_preview_video_key_videouploadsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videouploadsession',
            name='upload_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
