# Generated by Django 4.2.17 on 2026-04-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_videouploadsession_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videouploadsession',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('completing', 'Completing'), ('aborting', 'Aborting'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
