# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_videouploadsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='ai_payment_draft_response',
            field=models.TextField(
                blank=True,
                help_text='AI generated payment email draft response',
                max_length=8000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='client_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='negotiation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='payment_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('SUBMITTED', 'Submitted'),
                    ('NEEDS_INFO', 'Needs Info'),
                    ('APPROVED', 'Approved'),
                    ('AWAITING_CLIENT_CONFIRMATION', 'Awaiting Client Confirmation'),
                    ('PAYMENT_PENDING', 'Payment Pending'),
                    ('PAID', 'Paid'),
                    ('DELIVERED', 'Delivered'),
                    ('EXPIRED', 'Expired'),
                    ('REVOKED', 'Revoked'),
                    ('REJECTED', 'Rejected'),
                ],
                default='SUBMITTED',
                max_length=32,
            ),
        ),
    ]
