# Generated by Django 4.2.17 on 2026-04-23 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0040_widen_licenserequestauditlog_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryaccess',
            name='granted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleryaccess',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
